export const loveReasons = [
  "The way you sneeze like a tiny kitten. 🤧",
  "How you ask 'khaana khaya?' even on your busiest days. 🥹",
  "Your cute pouts when you are mildly annoyed at me. 🌸",
  "The way you call me 'Pagal' with so much love. ❤️",
  "How your voice immediately calms my overthinking mind. 📞",
  "The way you wink (even when you're just teasing me). 😉",
  "Your beautiful, deep eyes that I can look into forever. 👀",
  "How you support my dreams even when they sound crazy. ✨",
  "Your silly, goofy jokes that only you and I understand. 😂",
  "The warmth of your hugs where all my stress melts. 🤗",
  "How you look so pretty in oversized hoodies. 🧸",
  "The unique and sweet way you pronounce my name. 🤍",
  "How you remember the tiny details I completely forget. 📝",
  "Your kind heart that cares about every small animal. 🐱",
  "How you make even the most boring tasks feel like an adventure. 🎒",
  "The way you cross your arms when you're acting tough. 😠",
  "Your messy morning hair that is absolutely adorable. ☀️",
  "The peaceful way you look when you're asleep. 💤",
  "How you hold my hand tightly when crossing the road. 🤝",
  "The soft scent of your hair. 🌸",
  "Your sleepy voice notes that I play on repeat. 🎧",
  "How you make me want to be a better person every day. 🌱",
  "The way you handle my dramatic mood swings. 🎭",
  "How you smile when eating your absolute favorite food. 🍕",
  "Your gentle checks to make sure I slept well. 🌙",
  "The way you look under soft warm fairy lights. 🌟",
  "How you get genuinely excited about tiny surprises. 🎁",
  "Your cute typo-filled messages when you are half-asleep. 📱",
  "The sound of your laugh that instantly makes me laugh too. 😂",
  "Your endless patience with my stupid questions. 🧠",
  "How cool you look with your white sunglasses. 😎",
  "The way you dress up, looking like a real princess. 👑",
  "How you get shy and blush when I compliment you. 😳",
  "Your kind and beautiful soul that shines so bright. 🌟",
  "How you trust me with your deepest thoughts. 🤫",
  "The way you check if I reached home safely. 🏡",
  "How you make my heart skip a beat with a single text. 💓",
  "Your soft voice when you have just woken up. 🥱",
  "The way you say 'hmm' when listening to me intently. 🗣️",
  "How you hold onto my arm when we walk together. 🚶‍♂️🚶‍♀️",
  "Your unconditional love that makes me feel safe. 🏡",
  "How you make me smile at my phone in public like a fool. 📲",
  "The way you complain about how cold your hands are. ❄️",
  "How you celebrate my smallest achievements. 🏆",
  "Your cute, tiny yawns. 🥱",
  "The way you look at me when you think I'm not looking. 🥺",
  "How you make my worst days completely disappear. ☀️",
  "The way you call me your favorite person. 🥇",
  "Your cute reactions to my romantic messages. 💬",
  "How cozy you look wrapped up in a heavy blanket. 🛌",
  "The way you hold my fingers. 🤍",
  "How you always know exactly how to cheer me up. 🪄",
  "Your determination when trying to solve a puzzle. 🧩",
  "The way you tilt your head when you are confused. 🤷‍♀️",
  "How you share your favorite music with me. 🎵",
  "Your soft forehead kisses. 💋",
  "The way you play with your rings when thinking. 💍",
  "How you always stand up for me. 🛡️",
  "Your cute, soft cheeks that I love to pinch. 😊",
  "How you make me feel like the luckiest guy alive. 🍀",
  "The way you say 'Goodnight' with extra hearts. 💖",
  "Your funny reactions to scary movies. 👻",
  "How you make our coffee dates feel so magical. ☕",
  "The cute little sound you make when surprised. 😲",
  "Your loyalty and commitment to us. 🤝",
  "The way you respect and value my opinions. 🤍",
  "How you make our simple walks feel like a movie scene. 🎬",
  "Your soft laughter when I tickle you. 🤭",
  "The way you look when you're concentrate-reading. 📚",
  "How you make my heart do a little happy dance. 💃",
  "Your sweet habit of checking on me. 📞",
  "The way you say 'I miss you' out of nowhere. 🥺",
  "How you look wearing my oversized shirt. 👚",
  "Your cute anger when I eat your share of chocolate. 🍫",
  "The way you look under a rainy umbrella. ☔",
  "Your cute habit of biting your lip when thinking. 👄",
  "How you always have my back, no matter what. 🛡️",
  "The way you notice when I am feeling low. 🔍",
  "Your lovely, comforting handwriting. ✍️",
  "How you get sleepy exactly at 11 PM. 🕚",
  "The way you save my photos in a secret folder. 📁",
  "Your cute reactions when I tease you. 🤪",
  "How you make our room feel so cozy. 🏡",
  "The way you hold onto me when you are tired. 🧸",
  "Your soft touch that makes all pain go away. 🩹",
  "How you get happy over a simple cup of tea. ☕",
  "The way you call me 'Chimu' with that sweet voice. ❤️",
  "Your cute pouts when you want attention. 🥺",
  "How you make my future look so bright and beautiful. 🌅",
  "The way you share your food (even when you're hungry). 🍟",
  "Your beautiful, child-like innocence. 👶",
  "How you always encourage me to do my best. 🚀",
  "The way you sleep on my shoulder. 💤",
  "Your warm smile that cuts through any dark day. ☀️",
  "How you make me feel so valued and loved. 🤍",
  "The way you look at sunsets, glowing in the light. 🌅",
  "Your soft sigh of relief when we finally meet. 😌",
  "How you protect our relationship like a treasure. 💎",
  "The way you say 'I love you' back with extra warmth. 💖",
  "Simply because you are my Champudii, and I wouldn't change a single thing about you. 🪐"
];
